name       : haskell-hashable
version    : 1.2.4.0
release    : 2
source     :
    - http://hackage.haskell.org/package/hashable-1.2.4.0/hashable-1.2.4.0.tar.gz : fb9671db0c39cd48d38e2e13e3352e2bf7dfa6341edfe68789a1753d21bb3cf3
license    : BSD-3-Clause
component  : programming
summary    : This package defines a class, Hashable, for types that can be converted
    to a hash value.
description: |
    This package defines a class, Hashable, for types that can be converted to a hash value.
builddeps  :
    - ghc
    - haskell-text
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 hashable-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/hashable-$version.conf
