name       : haskell-hashable
version    : 1.3.0.0
release    : 7
source     :
    - https://hackage.haskell.org/package/hashable-1.3.0.0/hashable-1.3.0.0.tar.gz : 822e5413fbccca6ae884d3aba4066422c8b5d58d23d18b9ecb5c03273bb19ab4
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package defines a class, Hashable, for types that can be converted to a hash value.
description: |
    This package defines a class, Hashable, for types that can be converted to a hash value.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
