name       : haskell-hashable
version    : 1.4.2.0
release    : 8
source     :
    - https://hackage.haskell.org/package/hashable-1.4.2.0/hashable-1.4.2.0.tar.gz : 1b4000ea82b81f69d46d0af4152c10c6303873510738e24cfc4767760d30e3f8
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package defines a class, Hashable, for types that can be converted to a hash value.
description: |
    This package defines a class, Hashable, for types that can be converted to a hash value.
builddeps  :
    - ghc-devel
    - haskell-data-array-byte-devel
rundeps    :
    - devel : 
      - haskell-data-array-byte-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
