name       : haskell-hashable
version    : 1.2.4.0
release    : 3
source     :
    - http://hackage.haskell.org/package/hashable-1.2.4.0/hashable-1.2.4.0.tar.gz : fb9671db0c39cd48d38e2e13e3352e2bf7dfa6341edfe68789a1753d21bb3cf3
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package defines a class, Hashable, for types that can be converted
    to a hash value.
description: |
    This package defines a class, Hashable, for types that can be converted to a hash value.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
