name       : haskell-hashable
version    : 1.2.7.0
release    : 6
source     :
    - https://hackage.haskell.org/package/hashable-1.2.7.0/hashable-1.2.7.0.tar.gz : ecb5efc0586023f5a0dc861100621c1dbb4cbb2f0516829a16ebac39f0432abf
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package defines a class, Hashable, for types that can be converted
    to a hash value.
description: |
    This package defines a class, Hashable, for types that can be converted to a hash value.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
